---
- name: Change root Password
  user: name=root password={{ new_root_password }}
  when: new_root_password is defined

- name: Lock root User (use 'sudo passwd -u root' to re-enable)
  command: passwd -l root

- name: Remove sudo Group Rights
  lineinfile:
    dest:     /etc/sudoers
    regexp:   "^%sudo"
    state:    absent
    validate: "visudo -cf %s"

- name: Create Console User Account
  user:
    name:     "{{ console_user }}"
    password: "{{ console_user_password }}"
    shell:    /bin/bash
    state:    present
    groups:   www-data
    append:   yes

- name: Add Console User to Sudoers
  lineinfile:
    dest:     /etc/sudoers
    regexp:   "^{{ console_user }} ALL"
    line:     "{{ console_user }} ALL=(ALL) ALL"
    state:    present
    validate: "visudo -cf %s"

- name: Ensure Public Key is in authorized_keys
  authorized_key:
    user: "{{ console_user }}"
    key:  "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Install Bash Profile
  template: src=bashrc.j2 dest=/home/{{ console_user }}/.bashrc

- name: Update SSH Parameters
  lineinfile:
    dest:   /etc/ssh/sshd_config
    state:  present
    regexp: "^{{ item.key }}"
    line:   "{{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'Port',                   value: '{{ ssh_port | default("22") }}' }
    - { key: 'PermitRootLogin',        value: 'no' }
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'LoginGraceTime',         value: '20' }
    - { key: 'X11Forwarding',          value: 'no' }
    - { key: 'AllowUsers',             value: '{{ console_user }}' }
  notify: Restart SSH
