---
- name: Install Logwatch
  apt: pkg=logwatch state=installed

- name: Make Logwatch Mail {{ admin_email }} Daily
  lineinfile:
    dest: /etc/cron.daily/00logwatch
      regexp: "^/usr/sbin/logwatch"
      line:   "/usr/sbin/logwatch --output mail --mailto {{ admin_email }} --detail high"
      state:  present
      create: no
