---
- name: Install Nginx
  apt: package=nginx state=present
  sudo: yes

- name: Copy HTML5 Boilerplate's Nginx Configs
  copy: src=h5bp-nginx/ dest=/etc/nginx/h5bp
  sudo: yes
  notify: Restart Nginx

- name: Create Default Nginx Site for Missing Vhosts
  copy: src=nginx.default.conf dest=/etc/nginx/sites-available/default
  sudo: yes
  notify: Restart Nginx

- name: Enable Nginx Default Site
  file:
    src:   /etc/nginx/sites-available/default
    dest:  /etc/nginx/sites-enabled/default
    state: link
  sudo: yes
  notify: Restart Nginx

- name: Create Nginx Log Directory
  file: path=/var/log/nginx state=directory mode=0755 owner=www-data
  sudo: yes

- name: Create Main Nginx Coniguration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes
  notify: Restart Nginx

- name: Deploy HTML5 Boilerplate's Main Config
  template: src=h5bp-basic.conf.j2 dest=/etc/nginx/h5bp/basic.conf
  sudo: yes
  notify: Restart Nginx

- name: Copy mime.types
  file: src=mime.types dest=/etc/nginx/mime.types
  sudo: yes
  notify: Restart Nginx
