---
# test mail with the following command:
# echo "Mail test." | mail -s "Just Testing" <some_email@address>

- name: Set up Postfix Selections (main mailer type)
  command: echo "postfix postfix/main_mailer_type select Internet Site" | debconf-set-selections

- name: Set up Postfix Selections (mailname)
  command: echo "postfix postfix/mailname string localhost" | debconf-set-selections

- name: Set up Postfix Selections (destinations)
  command: >
    echo 'postfix postfix/destinations string localhost.localdomain, localhost' | debconf-set-selections

- name: Install Postfix
  apt: pkg=postfix state=present

- name: Set Postfix loopback-only
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: "^inet_interfaces"
    line:   "inet_interfaces = loopback-only"
    state:  present
  notify: Restart Postfix

- name: Set Postfix Hostname
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: "^myhostname"
    line:   "myhostname = {{ ansible_fqdn }}"
    state:  present
  notify: Restart Postfix

- name: Create root eMail Alias
  lineinfile:
    dest:   /etc/aliases
    regexp: "^root"
    line:   "root: {{ admin_email }}"
    state:  present
  notify: Restart Postfix
