---
- name: Remove Active Site Link
  file: path=/etc/nginx/sites-enabled/{{ domain }} state=absent
  sudo: yes
  notify: Restart Nginx

- name: Remove Nginx Site Config
  file: path=/etc/nginx/sites-available/{{ domain }} state=absent
  sudo: yes
  notify: Restart Nginx

- name: Remove PHP-FPM Pool Config
  file: path=/etc/php5/fpm/pool.d/{{ domain }}.conf state=absent
  sudo: yes
  notify:
    - Restart PHP-FPM
    - Restart Warpspeed PHP-FPM

- name: Delete Site Directory
  file: path={{ www_home }}/{{ domain }} state=absent
  when: purge is defined and purge

- name: Delete Remote Git Repository
  file: path={{ git_home }}/{{ domain }}.git state=absent
  sudo: yes
  when: purge is defined and purge

- name: Remove Entry from Local Hosts File
  local_action: 'lineinfile dest=/etc/hosts regexp="{{ domain }}$" state=absent'
  when: purge_host is defined and purge_host
