---
- name: Create MySQL Admin in Production
  hosts: production
  remote_user: "{{ console_user }}"

  vars_prompt:
    - name: mysql_pass
      prompt: "MySQL Admin Password"
      private: yes
    - name: new_mysql_user
      prompt: "New MySQL Username"
      private: no
    - name: new_mysql_pass
      prompt: "New MySQL User Password (MAKE IT SECURE!)"
      private: yes
      confirm: yes

  tasks:
  - include: tasks/mysql-admin.yml

  handlers:
  - include: handlers/main.yml
