---
- name: Create MySQL Admin in Vagrant
  hosts: vagrant
  remote_user: vagrant

  vars_prompt:
    - name: new_mysql_user
      prompt: "New MySQL Username"
      private: no
    - name: new_mysql_pass
      prompt: "MySQL User Password"
      private: yes
      confirm: yes

  tasks:
  - include: tasks/mysql-admin.yml

  handlers:
  - include: handlers/main.yml
