---
- name: Deploy Laravel Application to Production
  hosts: production
  remote_user: "{{ console_user }}"

  vars_prompt:
    - name: site_vars
      prompt: Name of site to deploy (omit '.yml')
      private: no

  tasks:
    - name: Load Site Parameters
      include_vars: site_vars/{{ site_vars }}.yml

    - name: Get Local Working Directory
      local_action: command pwd
      register: working_dir
      changed_when: false

    - name: Local Domain
      set_fact: site_dir={{ working_dir.stdout }}/../sites/{{ local_domain }}

    - name: Add Remote to Repository
      local_action: >
        command git -C {{ site_dir }} remote add {{ git_remote }}
        ssh://{{ console_user }}@{{ ansible_ssh_host }}:{{ ansible_ssh_port }}{{ git_home }}/{{ production_domain }}.git
      register: git_result
      failed_when: 'git_result.rc != 0 and ("remote {{ git_remote }} already exists" not in git_result.stderr)'
      changed_when: git_result.rc == 0

    - name: Push Repository using Git
      local_action: command git -C {{ site_dir }} push {{ git_remote }} master
      register: git_push_result
      changed_when: '"Everything up-to-date" not in git_push_result.stderr'
      notify:
        - Install Dependencies
        - Migrate Databases

    - name: Copy .env.php File
      copy:
        src:   "{{ site_dir }}/.env.php"
        dest:  "{{ www_home }}/{{ production_domain }}/.env.php"
        owner: "{{ console_user }}"
        group: www-data
        mode:  0640
      notify:
        - Install Dependencies
        - Migrate Databases

  handlers:
    - include: handlers/main.yml

    - name: Install Dependencies
      composer: working_dir={{ www_home }}/{{ production_domain }}

    - name: Migrate Databases
      command: /usr/bin/php {{ www_home }}/{{ production_domain }}/artisan migrate --force
      register: migrate_result
      changed_when: '"Nothing to migrate." not in migrate_result.stdout'
