---
- name: Initialize Production Server
  hosts: production
  remote_user: root

  vars_prompt:
    - name: console_user_password
      prompt: "Password for Console User (MAKE THIS SECURE!)"
      private: yes
      confirm: yes
      encrypt: md5_crypt
      salt_size: 7
    - name: admin_email
      prompt: "eMail Address for Notifications"
      private: no
    - name: mysql_pass
      prompt: "Password for MySQL Admin (MAKE THIS SECURE!)"
      private: yes
      confirm: yes

  tasks:
  - include: tasks/init-common.yml
  - include: tasks/lockdown_full.yml
  - include: tasks/fail2ban.yml
  - include: tasks/ufw.yml
  - include: tasks/postfix.yml

  handlers:
  - include: handlers/main.yml

  - name: Restart Server
    command: /sbin/reboot
    sudo: yes
