---
- name: Initializing Vagrant Box
  hosts: vagrant
  remote_user: vagrant

  tasks:
  - include: tasks/init-common.yml
  - include: tasks/site-create.yml
  - include: tasks/phpunit.yml

  handlers:
  - include: handlers/main.yml

  - name: Restart Server
    debug: msg="Run 'vagrant reload' after provisioning completes"
