---
- name: Add Ansible Support to Warpspeed Server
  hosts: production
  remote_user: warpspeed

  tasks:
    - include: tasks/warpspeed-env.yml
    - include: tasks/bash_profile.yml
    - include: tasks/nginx.yml
    - include: tasks/system_utilities.yml
    - include: tasks/php.yml

    - name: Add warpspeed User to www-data
      user:
        name:     "{{ console_user }}"
        groups:   www-data
        append:   yes

  handlers:
    - include: handlers/main.yml

    - name: Restart Server
      command: /sbin/reboot
      sudo: yes
